# Generated by Django 5.2.4 on 2025-07-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_pickup_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morning", "Morning (8 AM - 12 PM)"),
                    ("afternoon", "Afternoon (12 PM - 4 PM)"),
                    ("evening", "Evening (4 PM - 8 PM)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
